# Generated by Django 2.2.2 on 2019-06-12 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('priority', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['id', 'name', 'priority'], name='usuarios_us_id_b110b7_idx'),
        ),
    ]
