# Generated by Django 2.2.2 on 2019-06-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
